apiVersion: 1

policies:
  # Default: everything that hasn't been routed more specifically goes here.
  - orgId: 1
    receiver: google-chat-voicemedia
    group_by:
      - grafana_folder
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
